IF OBJECT_ID('dbo.LandmarkImages', 'U') IS NOT NULL 
  DROP TABLE dbo.LandmarkImages;
IF OBJECT_ID('dbo.LandmarkAudios', 'U') IS NOT NULL 
  DROP TABLE dbo.LandmarkAudios;
IF OBJECT_ID('dbo.Landmark', 'U') IS NOT NULL 
  DROP TABLE dbo.Landmark;


CREATE TABLE Landmark(
ID INT CHECK(ID>=0) PRIMARY KEY,
TITLE VARCHAR(30) NOT NULL,
LATITUDE FLOAT NOT NULL,
LONGITUDE FLOAT NOT NULL,
DESCRIPT VARCHAR(500) NOT NULL
);

CREATE TABLE LandmarkImages(
LANDMARK_ID INT FOREIGN KEY REFERENCES Landmark,
ID INT NOT NULL,
EXTENSION VARCHAR(5) NOT NULL CHECK(EXTENSION IN ('jpg', 'jpeg', 'gif','png'))
PRIMARY KEY(LANDMARK_ID,ID)
);

CREATE TABLE LandmarkAudios(
LANDMARK_ID INT FOREIGN KEY REFERENCES Landmark,
ID INT NOT NULL
PRIMARY KEY(LANDMARK_ID,ID)
)